### ISSUE TITLE
collect ideas on context strategy for SuppressionPatchFilter

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#7]
context - consider a wider context when new code introduces violations outside of new/changed lines

**Comment by timurt** [comment]
@HuGanghui let's discuss [this PR](https://github.com/checkstyle/patch-filters/pull/97) here.

> context - consider a wider context when new code introduces violations outside of new/changed lines, but let's presume it is on the same branch in AST but on upper level.

I think we can divide checks by the following criteria:
 - Checks, which throw violations for whole file
 - Checks, which throw violations for specific AST element

Probably `NewLineAtEndOfFile`, `RegexpOnFilename` and `FileLength` do not need AST tree and can be considered as first type

For the second type we should solve the following problem: If any child node of the violated node was changed during the patch, then violations are shown to user, otherwise they are suppressed.

**Comment by timurt** [comment]
Example:
```
$ cat InputTest.java 
public class InputTest {
    public void test() {
        int a = 123;
    }
}
```
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
  	  <module name="MethodLength">
              <property name="max" value="3"/>
          </module>
     <module name="SuppressionPatchFilter">
        <property name="patch" value="random.patch"/>
      </module>
    </module>
</module>
```

Here `random.patch` some random patch file, which does not contains changes for `test()` method.

```
$ java -jar checkstyle-8.xx-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /var/tmp/checkstyle/Test.java:2:5: Method length is 4 lines (max allowed is 3). [MethodLength]
Audit done.
Checkstyle ends with 1 errors.
```

By default this violation should be suppressed, because patch file contains no changes for `test()` method

--------

But if we replace patch file with another patch file, which contains updates in method, then violation should not be suppressed

```
$ cat 1.patch 
--- a/Test.java
+++ b/Test.java
@@ -2,5 +2,6 @@ public class InputTest {
     public void test() {
         int a = 123;
         int b = 234;
+        int c = 345;
     }
 }
```
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
  	  <module name="MethodLength">
              <property name="max" value="3"/>
          </module>
     <module name="SuppressionPatchFilter">
        <property name="patch" value="1.patch"/>
      </module>
    </module>
</module>
```
```
$ patch Test.java < 1.patch 
patching file Test.java
```
```
$ cat Test.java 
public class InputTest {
    public void test() {
        int a = 123;
        int b = 234;
        int c = 345;
    }
}
```
```
$ java -jar checkstyle-8.xx-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /var/tmp/checkstyle/Test.java:2:5: Method length is 5 lines (max allowed is 3). [MethodLength]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by timurt** [comment]
I would suggest the following approach for violations, which have access to AST tree:

1. Receive violation, extract corresponding AST node
2. Iterate all subnodes of the current node
3. If any subnode is inside changed code parts (we can reuse logic from `line` strategy), then violation is shown, otherwise suppressed

@rdiachenko @romani @HuGanghui share your thoughts

**Comment by HuGanghui** [comment]
@timurt yes, I agree with you ideas

**Comment by HuGanghui** [comment]
Another special case is `RegexpMultiline`, it is not TreeWalker Check, no AST tree and not for whole file.  

https://github.com/checkstyle/checkstyle/blob/ede1c75264d54c8c438f953ff9ea4d874b57b3ac/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/MultilineDetector.java#L93
```java
/** Method that finds the matches. */
    private void findMatch() {
        try {
            boolean foundMatch = matcher.find();

            while (foundMatch) {
                currentMatches++;
                if (currentMatches > options.getMaximum()) {
                    final LineColumn start = text.lineColumn(matcher.start());
                    if (options.getMessage().isEmpty()) {
                        options.getReporter().log(start.getLine(),
                                MSG_REGEXP_EXCEEDED, matcher.pattern().toString());
                    }
                    else {
                        options.getReporter()
                                .log(start.getLine(), options.getMessage());
                    }
                }
                foundMatch = matcher.find();
            }
        }
```

**Comment by romani** [comment]
@timurt , @HuGanghui , please do not share examples in issue, please create PR with test case.
line lenght is covered at  https://github.com/checkstyle/patch-filters/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/filters/MethodLine/MethodLineConfig.xml , but we need extra test case for LineLength with patch to unrelated lines. @HuGanghui , please do.

We should always talk in test driven way. If you think about test case - immediately create folder for it. Expected violations is discuss-able and will be determined before merge. BUT we have to have this test.

**Comment by romani** [comment]
@timurt , please lets keep discussion on Xpath related Filter in https://github.com/checkstyle/patch-filters/issues/8

**Comment by romani** [comment]
>  For example, violation's line is 5 not 6, if line 6 is added/patched, then this violation will be suppressed, which should not:

I do not understand this ....
let stop any attempts to have discussion like this. @HuGanghui , please send PR with Junit on thism with clear deinition on all files and expected result.

**Comment by timurt** [comment]
@romani 
Here test example https://github.com/checkstyle/patch-filters/pull/112

**Comment by romani** [comment]
@timurt , please do not mix filters.
In this issue we discuss filter and Checks from `Checker` (no AST, no xpath).
if you want to test how it will work when java code is modified and we have only SuppressionPatchFilter (no AST) configured. It is good test, and it is should suppress all violations that are not on same line. Please think on this, we might should have some property to do not consider violations that come from AST based Checks. Think about case when two filters are enabled together, Checker filter (SuppressionPatchFilter) will suppress all violations that a might pass SuppressionPatchXapthFilter (in case of context strategy, or mismatch of strategies between SuppressionPatchFilter and SuppressionPatchXapthFilter)

**Comment by timurt** [comment]
@romani 

> In this issue we discuss filter and Checks from Checker (no AST, no xpath).

Okay, you are right,
For `SuppressionPatchFilter` I see two types of checks:
- checks that always throws violation only on first line (RegexpOnFileName, FileLength and etc), @HuGanghui already implemented logic for them
- and other checks that throws violation on the corresponding line, for example `RegexpSingleline`
For second type I see simple logic:
`if there is violation and violation line is inside patch then violation is shown, otherwise suppressed` - I think it is same as `line` strategy, @HuGanghui correct me if I am wrong

> Think about case when two filters are enabled together, Checker filter (SuppressionPatchFilter) will suppress all violations that a might pass SuppressionPatchXapthFilter (in case of context strategy, or mismatch of strategies between SuppressionPatchFilter and SuppressionPatchXapthFilter)

What do you think about the following idea:
when we receive violations inside `SuppressionPatchFilter`,  we first check if there is `SuppressionPatchXapthFilter` filter inside configuration file. If `SuppressionPatchXapthFilter` exists, then we show violation to user, otherwise we check violation based on `SuppressionPatchFilter` logic

**Comment by romani** [comment]
> we first check if there is SuppressionPatchXapthFilter filter inside configuration file. 

no. Filters do not know about each other and filter do not know where config is located, there might be no config at all.
We need explain filter what Checks are Checker and what Checks from Treewalker.  We can use search Filter properties to specify names. We might type of Event and simply accept all TreeWalkerAuditEvent SuppressionPatchFilter. is it doable ?

**Comment by timurt** [comment]
@romani 

> We need explain filter what Checks are Checker and what Checks from Treewalker. 

hmm...makes sense. Are you suggesting that `SuppressionsPatchFilter` should ignore all violations from `TreeWalker` checks?

We can add property to `LocalizedMessage` for events came from `TreeWalker`. For example `isTreeWalkerEvent`, which is false by default and initialized explicitly somewhere in `TreeWalker.processFiltered`

or

If I am not wrong, all `TreeWalker` checks extend `AbstractCheck` class and `LocalizedMessage` has `sourceClass` property. So inside `SuppressionsPatchFilter` we can check, if event is from `AbstractCheck` subclasses or not.

**Comment by HuGanghui** [comment]
@timurt 

>all TreeWalker checks extend AbstractCheck class and LocalizedMessage has sourceClass property. So inside >SuppressionsPatchFilter we can check, if event is from AbstractCheck subclasses or not.

I agree with your idea, and now one problem is that `sourceClass` property is `private`, so if we want to use this solution, we should add `getSourceClass` method in `LocalizedMessage`.

**Comment by romani** [comment]
we can make getter for it , in this issue we already plan to allow access to it - https://github.com/checkstyle/checkstyle/issues/7884 

@HuGanghui , please send PR to main project.

**Comment by HuGanghui** [comment]
@romani ok, I read https://github.com/checkstyle/checkstyle/issues/7884, and not very clear about it, so I make a new issue https://github.com/checkstyle/checkstyle/issues/8602, and make a PR for it

**Comment by HuGanghui** [comment]
as mentioned in https://github.com/checkstyle/patch-filters/issues/7#issuecomment-659842057, `Header` also belongs to the first type.

**Comment by rdiachenko** [comment]
@HuGanghui what's the status of this issue?

**Comment by HuGanghui** [comment]
this issue has been fixed. no need more discussion.
