### ISSUE TITLE
collect ideas on context strategy for SuppressionPatchXpathFilter

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#8]
context - consider a wider context when new code introduces violations outside of new/changed lines, but let's presume it is on the same branch in AST but on upper level.

**Comment by HuGanghui** [comment]
As mentioned in https://github.com/checkstyle/patch-filters/issues/7#issuecomment-659847099 and https://github.com/checkstyle/patch-filters/pull/120#issue-454336145, this is a good context strategy for a kind of TreeWalker Checks that its violation just relate to its child nodes, such as MethodLength, MethodCount, RetrunCount. But not all. There is another kind of TreeWalker Checks that previous codes changed/added will affect its violation, such as JavadocMethod.

**Comment by baratali** [comment]
@romani , @timurt , @rdiachenko 
Question about context strategy.
Example ReturnCountCheck:
```java
class Test{
	int test(int a) {
		if (a == 1) {
			return 1;
		}
		if (a == 2) {
			return 2;
		}
		System.out.print(a);
	}
}
```
We already have violation because of two returns.
patch diff:
```diff
19:48 $ diff -U1 Test.java Test2.java 
--- Test.java	2020-07-21 19:49:55.097668656 +0100
+++ Test2.java	2020-07-21 19:49:47.089636449 +0100
@@ -8,3 +8,3 @@
 		}
-		System.out.print();
+		System.out.print(a);
 	}
```
The diff itself doesn't add any returns, but it changes method body. Do we expect that our new filter doesn't suppress a violation on method `test()` anymore because its body changed in patch file?

**Comment by romani** [comment]
I think we have no easy way to detect what violations on method are for suppression and what not , based on change from user.

We will not suppress all violations. We just need to keep violations that are around of changes.

In your case. There should be all violations that are placed on method.
But we might need to classify all checks on contextual and line based. To let us keep violation for some check, but in the same time suppress violations on method name.

Can you try to classify ?

**Comment by baratali** [comment]
> Can you try to classify ?

yes, will do

**Comment by timurt** [comment]
@baratali 

> The diff itself doesn't add any returns, but it changes method body. Do we expect that our new filter doesn't suppress a violation on method test() anymore because its body changed in patch file?

I think we should not suppress, because it was said previously in Telegram:
"If user started modifying method, it makes sense to show all violations related to this method"

@romani 

> I think we have no easy way to detect what violations on method are for suppression and what not , based on change from user.

Why? For example `ReturnCount` violations are thrown for method node, if method has any `git` modifications inside then violation is shown, suppressed otherwise

**Comment by romani** [comment]
I merged PR, but would like to review it one more time. So issue stay open as reminder to me

**Comment by HuGanghui** [comment]
According to many PRs about different checks' context strategy that I created, I agree with @timurt 's idea https://github.com/checkstyle/patch-filters/issues/7#issuecomment-659842057, but this idea can not solve all checks' context strategy, because some checks have their own problems, here is a summary which aims to find a common pattern:

* a kind of checks' problem is that  its violation node is on IDENT not METHOD_DEF (or other similar node whose child nodes contains all method/class's nodes), this problem will make our current context strategy not work.

> If any child node of the violated node was changed during the patch, then violations are shown to user, otherwise they are suppressed

relavant checks: 
* ParameterNumberCheck https://github.com/checkstyle/patch-filters/pull/130
* FinalLocalVariable https://github.com/checkstyle/patch-filters/pull/167
* SuperClone https://github.com/checkstyle/patch-filters/pull/181

**Comment by HuGanghui** [comment]
2. the second kind of checks's problem is that if we add/delete/change some nodes, then it will cause a violation, but these add/delete/change nodes are not violation node's child node, so current strategy not work.

relavant checks:

* AvoidNestedBlocks https://github.com/checkstyle/patch-filters/pull/137
* RightCurly https://github.com/checkstyle/patch-filters/pull/145
* ArrayTrailingComma https://github.com/checkstyle/patch-filters/pull/147
* DefaultComesLast https://github.com/checkstyle/patch-filters/pull/154
* UnnecessarySemicolonInEnumeration https://github.com/checkstyle/patch-filters/pull/183
---
* CovariantEquals https://github.com/checkstyle/patch-filters/pull/153
* HiddenField https://github.com/checkstyle/patch-filters/pull/168/

**Comment by HuGanghui** [comment]
3. the third kind of checks's problem is that some check is not Comments aware, comments are not appended to Tree.  But in these checks' comments nodes will cause a violation, but these comments nodes are not appended to Tree, so of course not violation node's child node, so current strategy not work.

relavant checks:
* MissingOverride https://github.com/checkstyle/patch-filters/pull/133

**Comment by HuGanghui** [comment]
4. the fourth kind of checks which throw only one violation for whole file. 

relavant checks:

* OuterTypeNumberCheck https://github.com/checkstyle/patch-filters/pull/120
* NoCodeInFileCheck https://github.com/checkstyle/patch-filters/pull/198

solution: add these checks to 
```java
/**
     * List of checks that always matching context strategy.
     */
    private static final List<String> ALWAYS_MATCHING_CONTEXT_STRATEGY_CHECKS
```
defined in `PatchXpathFilterElement.java`

**Comment by HuGanghui** [comment]
5. the fifth kind of checks, all violations' information line are the `0`, and violation information no node, just a line information:

relevant checks:

* Regexp https://github.com/checkstyle/patch-filters/pull/207

I think the solution is to  implement property similar to neverSuppressedChecks #108 in SuppressionPatchXpathFilter.

**Comment by HuGanghui** [comment]
6. the sixth kind of checks, checks belong to Javadoc module do not support ast tree, as mentioned in https://checkstyle.sourceforge.io/config_filters.html#SuppressionXpathFilter_Description

**Comment by rdiachenko** [comment]
@HuGanghui what's the status of this issue?

**Comment by HuGanghui** [comment]
this issue has been fixed, and more discussion can be found in https://github.com/checkstyle/patch-filters/issues/302.
