### ISSUE TITLE
Add Non-Treewalker filter tests to cover more cases

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#92]
Please add the following use cases:
1. A block of code contains violations and was moved from one file to another file **without** changes
2. A block of code contains violations and was moved within the same file **without** changes
3. A block of code contains violations and was moved from one file to another file **with** minor changes
4. A block of code contains violations and was moved within the same file **with** minor changes
5. A single **new** line of code contains violations
6. A single **changed** line of code contains violations

Tests should be added using the same approach as here https://github.com/checkstyle/patch-filters/issues/73

**Comment by HuGanghui** [comment]
@rdiachenko I have finish the first Checker - FileTabCharacter: https://github.com/checkstyle/patch-filters/pull/95. 

And during the process of completing the PR, I think about whether it was necessary to do this many cases for each Checker, because I think the different cases were essentially testing JGit to see if JGit would get the right rows in different situations. And this work actually has been done in https://github.com/checkstyle/patch-filters/pull/81 and https://github.com/checkstyle/patch-filters/pull/80, and it pass all test, so we can trust JGit works well, it will get the right rows that we want(add/patched) in different situations. **This is an important premise.**

But this issue's real purpose is to make sure every checker's added/patched lines' violation will be correctly captured, no extra, no more and no less. Actually for different checkers, based on the above premise that JGit will get the right rows that we want(add/patched) in different situations, what we actually need to do is to make a qualitative analysis (similar to https://github.com/checkstyle/patch-filters/issues/21#issuecomment-648743650) to know and confirm every checker's lineNo in violation information whether is same with added/changed line. And we can get the three conclusion:

* check whose violation line information is at where it was changed and violates rules
   these will be exactly captured by this line version's patch-filter, no extra, no more and no less.

* check whose violation line information is not at where it was changed and violates rules
 these check should be solved by context strategy.

**Comment by baratali** [comment]
@HuGanghui , I closed #74. Please add these remaining tests from #74 for one of the checks:

> there are only deleted lines in patch file

No violations expected from newline and patchedline strategies.

> there are only changed lines in patch file

Violations expected only from patchedline.

**Comment by rdiachenko** [comment]
Was merged in scope of https://github.com/checkstyle/patch-filters/pull/119.

All test cases mentioned above are present in master.
